// <auto-generated />
using System;
using GD.FinishingSystem.DAL.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GD.FinishingSystem.DAL.Migrations
{
    [DbContext(typeof(FinishingSystemContext))]
    [Migration("20210324220716_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("GD.FinishingSystem.Entities.RuloMigration", b =>
                {
                    b.Property<int>("RuloMigrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Beam")
                        .HasColumnType("int");

                    b.Property<int>("BeamLetter")
                        .HasColumnType("int");

                    b.Property<string>("BeamStop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleterID")
                        .HasColumnType("int");

                    b.Property<decimal>("GummedMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdaterID")
                        .HasColumnType("int");

                    b.Property<int>("Loom")
                        .HasColumnType("int");

                    b.Property<int>("Lote")
                        .HasColumnType("int");

                    b.Property<decimal>("Meters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NextMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceNo")
                        .HasColumnType("int");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuloMigrationID");

                    b.ToTable("tblRuloMigrations");
                });
            modelBuilder.Entity("GD.FinishingSystem.Entities.ViewModels.VMRuloReport", b =>
                {
                    b.Property<int>("Beam")
                        .HasColumnType("int");

                    b.Property<string>("BeamStop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanContinue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EntranceLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExitLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FolioNumber")
                        .HasColumnType("int");

                    b.Property<string>("IsToyota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsWaitingAnswerFromTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastRuloProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loom")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceCount")
                        .HasColumnType("int");

                    b.Property<int>("RuloID")
                        .HasColumnType("int");

                    b.Property<string>("RuloObservations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentAuthorizerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResultAuthorizer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResultObservations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("tblRuloReports");
                });

#pragma warning restore 612, 618
        }
    }
}
